version: '3'
services:
  db:
    image: mariadb:10.5-focal
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  wordpress:
    depends_on:
      - db
    build: .
    ports:
      - "${WORDPRES_EXTERNAL_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRES_EXTERNAL_HOST: ${WORDPRES_EXTERNAL_HOST}
      WORDPRES_EXTERNAL_PORT: ${WORDPRES_EXTERNAL_PORT}
      WORDPRES_THEME_NAME: ${WORDPRES_THEME_NAME}
    volumes:
      - ./wordpress/wp-content/themes/${WORDPRES_THEME_NAME}:/var/www/html/wp-content/themes/${WORDPRES_THEME_NAME}
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./docker/wp-config.php:/var/www/html/wp-config.php
      - ./wordpress/script:/script
  node:
    build: ./node
    tty: true
    environment:
      WORDPRES_THEME_NAME: ${WORDPRES_THEME_NAME}
    volumes:
      - ./node:/node
      - ./wordpress/wp-content/themes/${WORDPRES_THEME_NAME}:/wordpress/${WORDPRES_THEME_NAME}
    command: bash setup.sh